CREATe TABLE `user`(`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`name` TEXT CHARACTER SET utf8mb4 NOT NULL,`password` TEXT CHARACTER SET utf8mb4 NOT NULL);
ALTER TABLE `user` ADD CONSTRAINT `unique_username` UNIQUE(`name`(200));
CREATe TABLE `task`(`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`name` TEXT CHARACTER SET utf8mb4 NOT NULL,`expected_filename` TEXT CHARACTER SET utf8mb4 NOT NULL,`language` TEXT CHARACTER SET utf8mb4 NOT NULL,`tests` TEXT CHARACTER SET utf8mb4 NOT NULL,`description` TEXT CHARACTER SET utf8mb4 NOT NULL);
CREATe TABLE `result`(`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`user` BIGINT NOT NULL REFERENCES `user`,`task` BIGINT NOT NULL REFERENCES `task`,`program` TEXT CHARACTER SET utf8mb4 NOT NULL,`passed` TINYINT(1) NOT NULL,`output` TEXT CHARACTER SET utf8mb4 NOT NULL,`error` TEXT CHARACTER SET utf8mb4 NOT NULL);
ALTER TABLE `result` ADD CONSTRAINT `result_user_fkey` FOREIGN KEY(`user`) REFERENCES `user`(`id`);
ALTER TABLE `result` ADD CONSTRAINT `result_task_fkey` FOREIGN KEY(`task`) REFERENCES `task`(`id`);
