name:                service
version:             0.1.0.0
license:             BSD3

ghc-options:
- -Wall
- -Werror

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- esqueleto
- exceptions
- generic-lens
- microlens
- monad-logger
- mtl
- mysql
- path
- path-io
- persistent
- persistent-mysql
- persistent-template
- resource-pool
- servant
- servant-server
- text
- transformers
- typed-process
- unliftio-core
- warp

default-extensions:
- BlockArguments
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- GeneralisedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- TypeApplications
- TypeOperators

library:
  source-dirs: src

executables:
  service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - service
